kubeconfig: /path/to/kubeconfig
  name: bastion
  zone: asia-south1-a
  connections:
    - local_port: 5434
      remote_host: 10.116.48.59
      remote_port: 5432

rules:
  - namespace: enr
    app: cashfree
    local_port: 8080
    remote_port: 8080